[package]
name = "rustkit"
version = "0.1.0"
edition = "2021"

[lib]
name = "rustkit"
path = "src/lib.rs"

[dependencies]
axum = "0.6.0-rc.1"
once_cell = "1.13"
prometheus = "0.13"
tokio = { version = "1.0", features = ["full"] }
tower = "0.4"
