# SPDX-FileCopyrightText: 2022 Foundation Devices Inc. <hello@foundationdevices.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
version: '3'
services:
  servus-demo-postgres:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    ports:
      - "5432:5432"
