# SPDX-FileCopyrightText: 2022 Foundation Devices Inc. <hello@foundationdevices.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: rust
on: push
jobs:
  build-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --example echo
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
